OAuth2:
  # client_id: Q0tOS07vrybAgYQj30FzOvtgUc9WGxTlPkQjlnx51782RoQ52L
  # client_secret: 7lw2qSWf9cwyvweo6EO1MUCNw9EQvs2kWBNLNdCm
  client_id: Q0PvPlI6Vc6oEWJD4AeumjFSSLdQI4HSniUXk1weWXIGDJlawv
  client_secret: DWovZsQMp3X2WbEh0TWe73leq6jkFhaPpBaSVDpl
Constant:
  baseURL: https://appcenter.intuit.com/connect/oauth2
  tokenURL: https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer
  scope: com.intuit.quickbooks.accounting
  resfresh_grant_type: refresh_token
  response_type: code
  grant_type: authorization_code
Settings:
  # host_uri: https://4a9fe3eb.ngrok.io/
  # redirect_uri: https://4a9fe3eb.ngrok.io/token/new
  host_uri: http://localhost:8000/
  redirect_uri: http://localhost:8000/callback
  state: randomState
